steps:
  # Install Go and other necessary dependencies
  - name: 'golang:1.16'  # Use the appropriate Go version
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        apt-get update
        apt-get -y install git
        # Install Snyk CLI
        npm install -g snyk
        SNYK_TOKEN=${_SNYK_TOKEN}
        export SNYK_TOKEN

  # Build your Go project
  - name: 'golang:1.16'  # Use the same Go version as above
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        go build

  # Run Snyk SCA security scan
  - name: 'golang:1.16'  # Use the same Go version as above
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        snyk test
