steps:
  # Install Go and other necessary dependencies, Install Snyk CLI, and Run Snyk SCA security scan
  - name: 'golang:1.16'  # Use the appropriate Go version
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        apt-get update
        apt-get -y install git
        # Install Snyk CLI
        npm install -g snyk
        SNYK_TOKEN=${_SNYK_TOKEN}
        export SNYK_TOKEN
        # Build your Go project (in the root folder)
        go build
        # Run Snyk SCA security scan on the current directory
        snyk test .

