steps:
  - name: 'maven:3-jdk-11'
    entrypoint: bash
    args:
      - '-c'
      - 'export PATH=$PATH:/usr/local/sonar-scanner-x.y.z/bin'
  - name: 'maven:3-jdk-11'
    entrypoint: bash
    args:
      - '-c'
      - 'sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=goprojectanalysis -Dsonar.projectKey=goprojectanalysis-projectkey -Dsonar.login=f59f893b3eafa15e2bd3c7faa5895e1f9137404a'
